export const testquizanswers = [
  {
    id: 1,
    type: 'mcq',
    question: 'Which planet is known as the Red Planet?',
    options: ['Earth', 'Mars', 'Jupiter', 'Venus'],
    correctAnswer: 'Mars',
    userAnswer: 'Mars',
  },
  {
    id: 2,
    type: 'tf',
    question: 'The Great Wall of China is visible from space.',
    correctAnswer: false,
    userAnswer: true,
  },
  {
    id: 3,
    type: 'mcq',
    question: "Who wrote the play 'Romeo and Juliet'?",
    options: [
      'William Shakespeare',
      'Charles Dickens',
      'Jane Austen',
      'Mark Twain',
    ],
    correctAnswer: 'William Shakespeare',
    userAnswer: 'Mark Twain',
  },
  {
    id: 4,
    type: 'tf',
    question: 'Mount Everest is the tallest mountain in the world.',
    correctAnswer: true,
    userAnswer: true,
  },
  {
    id: 5,
    type: 'mcq',
    question: 'What is the capital of France?',
    options: ['Berlin', 'Madrid', 'Rome', 'Paris'],
    correctAnswer: 'Paris',
    userAnswer: 'Madrid',
  },
  {
    id: 6,
    type: 'tf',
    question: 'Penguins can fly.',
    correctAnswer: false,
    userAnswer: false,
  },
  {
    id: 7,
    type: 'mcq',
    question: "Which element has the chemical symbol 'O'?",
    options: ['Gold', 'Oxygen', 'Osmium', 'Oganesson'],
    correctAnswer: 'Oxygen',
    userAnswer: 'Oxygen',
  },
  {
    id: 8,
    type: 'tf',
    question: 'The Nile is the longest river in the world.',
    correctAnswer: true,
    userAnswer: false,
  },
  {
    id: 9,
    type: 'mcq',
    question: "Who is known as the 'Father of Computers'?",
    options: [
      'Albert Einstein',
      'Charles Babbage',
      'Isaac Newton',
      'Nikola Tesla',
    ],
    correctAnswer: 'Charles Babbage',
    userAnswer: 'Charles Babbage',
  },
  {
    id: 10,
    type: 'tf',
    question: 'The atomic number of hydrogen is 2.',
    correctAnswer: false,
    userAnswer: true,
  },
  {
    id: 11,
    type: 'mcq',
    question: 'What is the hardest natural substance on Earth?',
    options: ['Gold', 'Iron', 'Diamond', 'Platinum'],
    correctAnswer: 'Diamond',
    userAnswer: 'Gold',
  },
  {
    id: 12,
    type: 'tf',
    question: 'The human body has four lungs.',
    correctAnswer: false,
    userAnswer: false,
  },
  {
    id: 13,
    type: 'mcq',
    question: 'What is the smallest country in the world?',
    options: ['Monaco', 'Nauru', 'San Marino', 'Vatican City'],
    correctAnswer: 'Vatican City',
    userAnswer: 'Nauru',
  },
  {
    id: 14,
    type: 'tf',
    question: 'Lightning never strikes the same place twice.',
    correctAnswer: false,
    userAnswer: false,
  },
  {
    id: 15,
    type: 'mcq',
    question: 'Who painted the Mona Lisa?',
    options: [
      'Vincent Van Gogh',
      'Claude Monet',
      'Leonardo da Vinci',
      'Pablo Picasso',
    ],
    correctAnswer: 'Leonardo da Vinci',
    userAnswer: 'Leonardo da Vinci',
  },
];
